### ISSUE TITLE
Joshua 21 - Error in Verses 36-37: Em Dashes 'u\2014' 

### ISSUE THREAD

**Issue by TorahBibleCodes** [bdenckla/MAM-for-Sefaria#3]
בע"ה

Hi.

I have integrated the MAM into our TorahBibleCodes program.

Insodoing - while doing QA testing that the integration was smooth and seamless - I was testing for the entire section of the Prophets, and encountered the same error that I encountered in the Book of Joshua (all other books and sections of books were working perfectly) - only for Joshua and the Prophets section as a whole did the following exception get thrown:

`UnboundLocalError: cannot access local variable 'value' where it is not associated with a value`

Upon further investigation, and confirming it in the source texts on the MAM repo (and adding the piece of code to account for these two em dashes only in Joshua 21:36-37 (MAM codex) I can confirm:

I have encountered an error in MAM in Joshua 21:36-37 that shows em dashes (Python Unicode `'\u2014'`) that made the word counter for the TorahBibleCodes throw an exception - when it should have worked seamlessly.

I looked at the Koren text, and indeed there are no two consecutive verses there that contain only em dashes.

Therefore, I would like to report this as an error/issue in the MAM codex current version of edit/update.

QUESTION:  What is the difference between your CSV and CSV-AJF versions of the codices?
https://github.com/bdenckla/MAM-for-Sefaria/tree/main/out

SCREENSHOTS:
![image](https://github.com/bdenckla/MAM-for-Sefaria/assets/33508112/8e405bee-0763-4ccf-a24b-fff99e058d7b)

![image](https://github.com/bdenckla/MAM-for-Sefaria/assets/33508112/0468d0b0-1ae9-4399-9797-94e7306cc138)

![image](https://github.com/bdenckla/MAM-for-Sefaria/assets/33508112/554da1b8-3560-475c-85e1-86e0e9f902ad)

**Comment by TorahBibleCodes** [comment]
Here is what it looks like when I run the entire MAM Tanach through the TorahBibleCodes program.

As you can see, it is just these two verses of Joshua 21:36-37 that need to be deleted from the source text as errors in order to recalibrate the text with the correct verse numbers.

![image](https://github.com/bdenckla/MAM-for-Sefaria/assets/33508112/0e96897d-e02c-4e32-9ff0-08c179202fba)

**Comment by bdenckla** [comment]
There's no error here, these "empty" verses (dash only) are intentional in order to correspond to Sefaria verse numbering.

You can learn more about this from my essay on the subject, ["Undoing and redoing the work of the Masoretes – Part 3: Extra verses"](https://docs.google.com/document/d/18IbvlmJ3PBIcN1d2rpAv989jspu6eGKvrMqZTeSMBHA/edit?usp=sharing). But that essay might not interest you since in the past you have refused to acknowledge the legitimacy of verse numbering schemes other than the one "true" scheme you seem to have in mind.

Don't jump to the conclusion that things you don't expect are errors, at least until you become more familiar with the differing verse numbering schemes of the Hebrew Bible.

It is fine to ask questions. But it is not fine when you assume you already know the answer and the answer is that a well-vetted edition such as MAM has a large error on the scale of verses, that somehow only you have noticed. Such an error is not impossible, but I will be more inclined to help you if you approach such a situation with the humility to assume that such an error is unlikely.

In a [different context](https://github.com/bdenckla/MAM-for-Sefaria/issues/2#issuecomment-2125399030) you even go so far to refer to a similar difference in verse numbering as "corruption," an even more loaded word than "error".

**Comment by TorahBibleCodes** [comment]
Hi Ben,

It would be really nice if you would stop continuing to speak with utter
disrespect and stop lecturing…

…and perhaps this time you should read the content in your own link… that
you wrote:

Since it is read only, here are the screenshots:

**Comment by TorahBibleCodes** [comment]
Error or not an error?

Error when you write an article, but not an error?

**Comment by TorahBibleCodes** [comment]
Yes, Ben:

Addition = Corruption = Error.

…but don’t take my word for it.

Just be consistent with what you wrote.

“Became polluted… error.”

Ahem.

**Comment by TorahBibleCodes** [comment]
…and whereas you assume omission of these two verses, the absence of these
verses in Leningrad and Koren and Aleppo and Sassoon codices is more likely
suggestive that these two verses are additions because of Occam’s Razor.

FYI - Sassoon is known to be a sloppy manuscript from a sloppy scribe in
general. Just saying… it may be ok here.

**Comment by TorahBibleCodes** [comment]
…ahem… omission or addition? Mistake or corruption?

Occam’s Razor…

**Comment by bdenckla** [comment]
I'm not seeing any screen shots from on my end, but I think I understand what you're referring to in my essay. In my essay I say:

> WLC should have omitted these verses or found a way to mark them with a semantic equivalent to BHS’s small type.

"[Omitting] these verses" is basically what I do in MAM for Sefaria, by supplying only dashes. It is the closest to truly omitting the verses I could come, while still obeying Sefaria's verse numbering, which includes numbers for these verses. In other words, in MAM for Sefaria, I omit the contents of these verses, and I was not free to omit the numbers for these verses, so I did not omit the numbers. Other editions of MAM omit not only the contents of these verses but the numbers, too.

We're not using the same vocabulary, since you make no distinction between the underlying content of a Hebrew Bible and its (to me, superficial) verse numbering.

Once again, we are at an unproductive impasse, since we disagree so fundamentally on whether verse numbers are fundamental or superficial to a Hebrew Bible.

So, once again, we're done here, unless there's a technical question I can answer, in which case please open up a new issue.

**Comment by bdenckla** [comment]
> Hi Ben, It would be really nice if you would stop continuing to speak with utter disrespect and stop lecturing

We both feel disrespected, since I find your knee-jerk assumptions that MAM is in error or corrupt to be disrespectful. All the more reason to cease this unproductive interchange.

**Comment by TorahBibleCodes** [comment]
Ben,

If you feel disrespected because of errors issues found , then you need to
realize that you are not your ideas or opinions and you are not married to
them, and they are not you.

… but you have intentionally disrespected me several times in writing
because of your ego.

Yet yourself wrote that these are errors.

I see the screenshots fine in the message history.

If you don’t see, then go read your article again, and the hypocrisy of
your lecturing me about humility…

Read your own words in your own article: these are errors when convenient
for you.
